In [369]:
#install Selenium library
! pip install selenium

Requirement already satisfied: selenium in c:\users\acer\anaconda3\lib\site-packages (4.2.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\acer\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: urllib3[secure,socks]~=1.26 in c:\users\acer\anaconda3\lib\site-packages (from selenium) (1.26.9)
Requirement already satisfied: trio~=0.17 in c:\users\acer\anaconda3\lib\site-packages (from selenium) (0.21.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\acer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: cffi>=1.14 in c:\users\acer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: sniffio in c:\users\acer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in c:\users\acer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: outcome in c:\users\acer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: sortedcontainers in c:\users\acer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\acer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: pycparser in c:\users\acer\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\acer\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.1.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\acer\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\acer\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (21.0.0)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\acer\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (3.4.8)
Requirement already satisfied: certifi in c:\users\acer\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (2021.10.8)
Requirement already satisfied: six>=1.5.2 in c:\users\acer\anaconda3\lib\site-packages (from pyOpenSSL>=0.14->urllib3[secure,socks]~=1.26->selenium) (1.16.0)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\acer\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.13.0)

In [431]:
#import required libraries
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
import time

In [417]:
#Lets first connect to the webdriver
driver=webdriver.Chrome(r"C:\chromedriver.exe")

In [372]:
#Q1: Write a python program to scrape data for “Data Analyst” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name, experience_required. You have to scrape first 10 jobs data.

#opening up naukri.com website on automated chrome window
driver.get('https://www.naukri.com/')

#finding element for job search bar
search_field_designation=driver.find_element_by_class_name("suggestor-input ") #job search bar
search_field_designation.send_keys("Data Analyst")

#entering location Bangalore in location search bar 
search_field_location=driver.find_element_by_xpath("/html/body/div/div[2]/div[3]/div/div/div[5]/div/div/div/input") #location search
search_field_location.send_keys("Bangalore")

#clicking on search button
search_button=driver.find_element_by_xpath("/html/body/div/div[2]/div[3]/div/div/div[6]") #location search
search_button.click()

job_titles=[]                     #list to store job titles
company_names=[]                  #list to store company names
loc=[]                            #list to store location
experience_list=[]                #list to store experience
    
#Lets extract all the tags having the job titles
title_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']") #locating web element of title

#Now the text of the job title is inside the tag extracted above
for i in title_tags[0:10]:
    titles=i.text
    job_titles.append(titles)

#Lets extract all the tags having the location
locations_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]") #locating web element of company name

#Now the location is inside the tag extracted above
for i in locations_tags[0:10]:
    location=i.text
    loc.append(location)

#Lets extract all the tags having the company names
companies_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']") #locating web element of company name

#Now the text of the company name is inside the tag extracted above
for i in companies_tags[0:10]:
    company_name=i.text
    company_names.append(company_name)

#Lets extract all the tags having the experience requirement
experience_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']/span") #locating web element of company name

#Now the experience requirement is inside the tag extracted above
for i in experience_tags[0:10]:
    experience=i.text
    experience_list.append(experience)

pd.set_option("display.max_rows", None, "display.max_columns", None)                #To display the entire dataframe
df1=pd.DataFrame({'Job Title':job_titles, 'Job Location':loc, 'Company Name':company_names, 'Experience Required':experience_list})
print("The data for “Data Analyst” Job position in “Bangalore” location")
df1

The data for “Data Analyst” Job position in “Bangalore” location

,Job Title,Job Location,Company Name,Experience Required
0,Business Data Analyst,Bangalore/Bengaluru,NXP Semiconductors,2-5 Yrs
1,EY GDS Data Analyst-Finland based project,Bangalore/Bengaluru,EY,0-1 Yrs
2,Data Analyst - Data and Analytics,Bangalore/Bengaluru,Intel,3-6 Yrs
3,Data Analyst - Data and Analytics,Bangalore/Bengaluru,Intel,3-6 Yrs
4,Data Analyst (CSD),Bangalore/Bengaluru,Siemens,2-6 Yrs
5,"Data Analyst - Data Science, 3 To 5 Years",Bangalore/Bengaluru,Rise Finconnect Private Limited,2-6 Yrs
6,Data Analyst / Business Analyst,Bangalore/Bengaluru,METRO Cash & Carry,3-8 Yrs
7,Data Analyst,Bangalore/Bengaluru,Cigna TTK,2-4 Yrs
8,SAS/SQL - Healthcare Data Analyst - Bangalore,Bangalore/Bengaluru,Genpact,7-10 Yrs
9,Business & Data Analyst - Alteryx (London),"Bangalore/Bengaluru, Delhi / NCR, Mumbai (All ...",Imaginative Brains LLP,5-10 Yrs

In [373]:
#Q2: Write a python program to scrape data for “Data Scientist” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name. You have to scrape first 10 jobs data.

#opening up naukri.com website on automated chrome window
driver.get('https://www.naukri.com/')

#finding element for job search bar
search_field_designation=driver.find_element_by_class_name("suggestor-input ") #job search bar
search_field_designation.send_keys("Data Scientist")

#entering location Bangalore in location search bar
search_field_location=driver.find_element_by_xpath("/html/body/div/div[2]/div[3]/div/div/div[5]/div/div/div/input") #location search
search_field_location.send_keys("Bangalore")

#clicking on search button
search_button=driver.find_element_by_xpath("/html/body/div/div[2]/div[3]/div/div/div[6]") #location search
search_button.click()

job_titles=[]                     #list to store job titles
company_names=[]                  #list to store company names
loc=[]                            #list to store location

#Lets extract all the tags having the job titles
title_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']") #locating web element of title

#Now the text of the job title is inside the tag extracted above
for i in title_tags[0:10]:
    titles=i.text
    job_titles.append(titles)

#Lets extract all the tags having the location
locations_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]") #locating web element of company name

#Now the location is inside the tag extracted above
for i in locations_tags[0:10]:
    location=i.text
    loc.append(location)

#Lets extract all the tags having the company names
companies_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']") #locating web element of company name

#Now the text of the company name is inside the tag extracted above
for i in companies_tags[0:10]:
    company_name=i.text
    company_names.append(company_name)

pd.set_option("display.max_rows", None, "display.max_columns", None)                #To display the entire dataframe
df2=pd.DataFrame({'Job Title':job_titles, 'Job Location':loc, 'Company Name':company_names})
print("The data for “Data Scientist” Job position in “Bangalore” location")
df2

The data for “Data Scientist” Job position in “Bangalore” location

,Job Title,Job Location,Company Name
0,Senior Data Scientist,"Mumbai, Bangalore/Bengaluru",Baker Hughes
1,Data Science - Engineering Manager,"Noida, Mumbai, Bangalore/Bengaluru",Paytm
2,AI Technologist Vacancy,"Kolkata, Hyderabad/Secunderabad, Pune, Ahmedab...",Wipro
3,Job Opening with Wipro For Data Scientist posi...,"Kolkata, Hyderabad/Secunderabad, Chennai, Bang...",Wipro
4,DATA Scientist with Fraud Analytics Experience,Bangalore/Bengaluru,Concentrix Daksh Services
5,Data Scientist,Bangalore/Bengaluru,Applied Materials
6,Data Scientist,Bangalore/Bengaluru,Applied Materials
7,Data Scientist,Bangalore/Bengaluru,Applied Materials
8,Data Scientist,Bangalore/Bengaluru,Applied Materials
9,Principal - Data Scientist,Bangalore/Bengaluru,Schneider Electric

In [382]:
#Q3: In this question you have to scrape data using the filters available on the webpage- You have to use the location and salary filter.You have to scrape data for “Data Scientist” designation for first 10 job results.You have to scrape the job-title, job-location, company name, experience required.The location filter to be used is “Delhi/NCR”. The salary filter to be used is “3-6” lakhs

#opening up naukri.com website on automated chrome window
driver.get('https://www.naukri.com/')

#finding element for job search bar
search_field_designation=driver.find_element_by_class_name("suggestor-input ") #job search bar
search_field_designation.send_keys("Data Scientist")

#clicking on search button                  
search_button=driver.find_element_by_xpath("/html/body/div/div[2]/div[3]/div/div/div[6]") #location search
search_button.click()

time.sleep(5)
#applying location filter           
driver.get('https://www.naukri.com/jobs-in-india?roleTypeFilterGid=169&cityTypeGid=9508&clusters=roleGid,citiesGid')

time.sleep(5)
#applying salary filter              
driver.get('https://www.naukri.com/jobs-in-india?clusters=roleGid,citiesGid&roleTypeFilterGid=169&cityTypeGid=9508&ctcFilter=3to6')

job_titles=[]                     #list to store job titles
company_names=[]                  #list to store company names
loc=[]                            #list to store location
experience_list=[]                #list to store experience

time.sleep(5)
#Lets extract all the tags having the job titles
title_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']") #locating web element of title

#Now the text of the job title is inside the tag extracted above
for i in title_tags[0:10]:
    titles=i.text
    job_titles.append(titles)

#Lets extract all the tags having the location
locations_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]") #locating web element of company name

#Now the location is inside the tag extracted above
for i in locations_tags[0:10]:
    location=i.text
    loc.append(location)

#Lets extract all the tags having the company names
companies_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']") #locating web element of company name

#Now the text of the company name is inside the tag extracted above
for i in companies_tags[0:10]:
    company_name=i.text
    company_names.append(company_name)

#Lets extract all the tags having the experience requirement
experience_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']/span") #locating web element of company name

#Now the experience requirement is inside the tag extracted above
for i in experience_tags[0:10]:
    experience=i.text
    experience_list.append(experience)

pd.set_option("display.max_rows", None, "display.max_columns", None)                #To display the entire dataframe
df3=pd.DataFrame({'Job Title':job_titles, 'Job Location':loc, 'Company Name':company_names, 'Experience Required':experience_list})
print("The data for Data Scientist Job position in Delhi/NCr location with 3-6 lakhs salary")
df3

The data for Data Scientist Job position in Delhi/NCr location with 3-6 lakhs salary

,Job Title,Job Location,Company Name,Experience Required
0,Job Opening with Wipro For Data Scientist posi...,"Kolkata, Hyderabad/Secunderabad, Chennai, Bang...",Wipro,2-7 Yrs
1,Data Scientist - Machine learning AI,"Bangalore/Bengaluru, Delhi / NCR, Mumbai (All ...",Teq Analytics,3-8 Yrs
2,Data Scientist -Machine Learning with Python,"Noida, New Delhi, Gurgaon/Gurugram, Delhi / NCR",Genpact,1-4 Yrs
3,Data Scientist,"Pune, Gurgaon/Gurugram, Bangalore/Bengaluru",SS Supply Chain Solutions Pvt. Ltd. (3SC),2-5 Yrs
4,Data Scientist - MIND Infotech,Noida,MOTHERSONSUMI INFOTECH & DESIGNS LIMITED,4-8 Yrs
5,Data Scientist - MIND Infotech,Noida,MOTHERSONSUMI INFOTECH & DESIGNS LIMITED,4-8 Yrs
6,Data Scientist - Predictive Analytics,"Noida, Mumbai, Chandigarh, Hyderabad/Secundera...",Confidential,1-6 Yrs
7,Data Scientist - Internet Jobs - II,"Bangalore/Bengaluru, Delhi / NCR, Mumbai (All ...",Jobs Territory,3-6 Yrs
8,Machine Learning Engineer | Data Engineer | Da...,"Chennai, Bangalore/Bengaluru, Delhi / NCR(Sect...",Tidyquant (OPC) Private Limited,1-3 Yrs
9,Hiring || Data Scientist || North Delhi || 5.5...,Delhi / NCR(Netaji Subhash Place),Shriram Automall India Limited,4-9 Yrs

In [400]:
#Q4: Scrape data of first 100 sunglasses listings on flipkart.com. You have to scrape four attributes: 1. Brand 2. Product Description 3. Price

#opening up flipkart.com website on automated chrome window
driver.get('https://www.flipkart.com/')

#finding element in search bar
search_field=driver.find_element_by_class_name("_3704LK") #search bar
search_field.send_keys("sunglasses")

#clicking on search icon
search_icon=driver.find_element_by_xpath("/html/body/div/div/div[1]/div[1]/div[2]/div[2]/form/div/button") #location search
search_icon.click()

brand=[]                    #list to store brand
product=[]                  #list to store product description
price=[]                    #list to store price
discount=[]                 #list to store discount

for j in range (0,3):    
    time.sleep(5)
    #Lets extract all the tags having the brand
    brand_tags=driver.find_elements_by_xpath("//div[@class='_2WkVRV']") #locating web element of brand
    for i in brand_tags:                 
        titles=i.text
        brand.append(titles)
     
    #Lets extract all the tags having the product description
    product_tags=driver.find_elements_by_xpath("//a[@class='IRpwTa']") #locating web element of product description
    
    #Now the text of the product description is inside the tag extracted above
    for i in product_tags:
        products=i.text
        product.append(products)
            
    #Lets extract all the tags having the price
    price_tags=driver.find_elements_by_xpath("//div[@class='_30jeq3']") #locating web element of price
    
    #Now the text of the price is inside the tag extracted above
    for i in price_tags:
        prices=i.text
        price.append(prices) 
   
    #Lets extract all the tags having the discount
    discount_tags=driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']/span") #locating web element of discount
    
    #Now the discount is inside the tag extracted above
    for i in discount_tags:
        discounts=i.text
        discount.append(discounts)
    
    #Now clicking on the next button
    if j==0:                                     #xpath for next butto fo 1st page and upcoming pages are different
        time.sleep(5)
        next_button=driver.find_element_by_xpath("/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[11]/span")
        next_button.click()
        time.sleep(5)
    else:
        time.sleep(5)
        next_button=driver.find_element_by_xpath("/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[12]/span")
        next_button.click()
        time.sleep(5)

pd.set_option("display.max_rows", None, "display.max_columns", None)                #To display the entire dataframe
df4=pd.DataFrame({'Brand':brand[0:100], 'Product description':product[0:100], 'Price': price[0:100], 'Discount Provided': discount[0:100]})
print("The data for sunglasses-")
df4

The data for sunglasses-

,Brand,Product description,Price,Discount Provided
0,Singco India,"Gradient, Toughened Glass Lens, UV Protection ...",₹598,80% off
1,ROZZETTA CRAFT,"UV Protection, Gradient Rectangular Sunglasses...",₹449,77% off
2,PIRASO,UV Protection Aviator Sunglasses (54),₹224,85% off
3,SRPM,UV Protection Wayfarer Sunglasses (50),₹211,83% off
4,Fastrack,UV Protection Wayfarer Sunglasses (Free Size),₹799,20% off
5,Elligator,UV Protection Round Sunglasses (54),₹295,88% off
6,Mi,Polarized Aviator Sunglasses (Free Size),₹839,30% off
7,ROZZETTA CRAFT,UV Protection Round Sunglasses (Free Size),₹399,85% off
8,Fastrack,UV Protection Rectangular Sunglasses (Free Size),₹639,20% off
9,Mi,Polarized Aviator Sunglasses (Free Size),₹854,28% off
10,PIRASO,UV Protection Aviator Sunglasses (54),₹224,85% off
11,ROZZETTA CRAFT,"UV Protection, Gradient Rectangular Sunglasses...",₹399,80% off
12,New Specs,UV Protection Rectangular Sunglasses (Free Size),₹264,89% off
13,PIRASO,UV Protection Rectangular Sunglasses (52),₹306,88% off
14,PIRASO,UV Protection Aviator Sunglasses (58),₹359,86% off
15,ROZZETTA CRAFT,UV Protection Spectacle Sunglasses (Free Size),₹399,80% off
16,ROZZETTA CRAFT,"Polarized, Riding Glasses Sports, Wrap-around ...",₹499,75% off
17,ROZZETTA CRAFT,UV Protection Rectangular Sunglasses (Free Size),₹319,78% off
18,Fastrack,UV Protection Aviator Sunglasses (58),"₹1,039",20% off
19,ROZZETTA CRAFT,"UV Protection, Gradient Round Sunglasses (Free...",₹399,80% off
20,SUNBEE,"UV Protection, Polarized Wayfarer Sunglasses (...",₹283,78% off
21,ROZZETTA CRAFT,"UV Protection, Gradient Retro Square Sunglasse...",₹349,82% off
22,VINCENT CHASE,"by Lenskart Polarized, UV Protection Cat-eye S...",₹929,53% off
23,VINCENT CHASE,UV Protection Wayfarer Sunglasses (59),₹649,67% off
24,SHAAH COLLECTIONS,"UV Protection, Polarized, Mirrored Rectangular...",₹195,88% off
25,Fastrack,UV Protection Aviator Sunglasses (Free Size),₹639,20% off
26,New Specs,"Mirrored, UV Protection, Riding Glasses, Other...",₹299,81% off
27,ROZZETTA CRAFT,UV Protection Round Sunglasses (Free Size),₹398,80% off
28,PIRASO,UV Protection Aviator Sunglasses (54),₹246,84% off
29,SRPM,"Others Wayfarer, Retro Square Sunglasses (50)",₹219,78% off
30,United Colors of Benetton,Gradient Cat-eye Sunglasses (57),₹929,74% off
31,john jacobs,UV Protection Round Sunglasses (53),"₹3,500",30% off
32,SUNBEE,"UV Protection, Polarized, Mirrored Retro Squar...",₹259,80% off
33,PHENOMENAL,"UV Protection, Mirrored Clubmaster Sunglasses ...",₹349,82% off
34,ROZZETTA CRAFT,UV Protection Retro Square Sunglasses (Free Size),₹499,77% off
35,VINCENT CHASE,UV Protection Rectangular Sunglasses (52),₹699,65% off
36,SRPM,"Night Vision, UV Protection Round Sunglasses (54)",₹233,76% off
37,Lee Topper,UV Protection Cat-eye Sunglasses (Free Size),₹259,80% off
38,AISLIN,"UV Protection, Gradient Butterfly, Retro Squar...",₹483,68% off
39,ROZZETTA CRAFT,UV Protection Round Sunglasses (Free Size),₹395,85% off
40,PHENOMENAL,"UV Protection, Mirrored Clubmaster Sunglasses ...",₹349,82% off
41,Lee Topper,UV Protection Cat-eye Sunglasses (Free Size),₹259,80% off
42,Elligator,UV Protection Round Sunglasses (53),₹219,78% off
43,VINCENT CHASE,by Lenskart UV Protection Wayfarer Sunglasses ...,₹899,55% off
44,AISLIN,"UV Protection, Gradient Butterfly, Retro Squar...",₹483,68% off
45,GANSTA,"Gradient, UV Protection Retro Square, Wayfarer...",₹233,87% off
46,AISLIN,"UV Protection, Gradient Retro Square Sunglasse...",₹498,67% off
47,ROZZETTA CRAFT,UV Protection Aviator Sunglasses (62),₹649,74% off
48,AISLIN,"UV Protection, Gradient Oval Sunglasses (58)",₹498,67% off
49,PIRASO,UV Protection Over-sized Sunglasses (65),₹410,84% off
50,PIRASO,UV Protection Aviator Sunglasses (54),₹223,86% off
51,agera,Gradient Aviator Sunglasses (55),₹242,78% off
52,Fastrack,UV Protection Aviator Sunglasses (58),"₹1,039",20% off
53,Fastrack,UV Protection Shield Sunglasses (Free Size),₹719,20% off
54,Urbanic,Others Oval Sunglasses (Free Size),₹499,49% off
55,john jacobs,UV Protection Clubmaster Sunglasses (47),"₹3,900",35% off
56,ROYAL SON,Polarized Rectangular Sunglasses (60),₹699,65% off
57,SHAAH COLLECTIONS,UV Protection Round Sunglasses (Free Size),₹279,78% off
58,VINCENT CHASE,"by Lenskart Polarized, UV Protection Round Sun...",₹929,53% off
59,john jacobs,UV Protection Round Sunglasses (54),"₹2,500",50% off
60,GHAWK,UV Protection Rectangular Sunglasses (Free Size),₹299,70% off
61,ROZZETTA CRAFT,"UV Protection, Gradient Rectangular Sunglasses...",₹399,80% off
62,Fastrack,UV Protection Shield Sunglasses (Free Size),₹809,10% off
63,AISLIN,"UV Protection, Gradient Oval Sunglasses (58)",₹498,67% off
64,Fastrack,UV Protection Wayfarer Sunglasses (Free Size),₹759,15% off
65,VINCENT CHASE,by Lenskart UV Protection Aviator Sunglasses (...,"₹1,179",41% off
66,ROYAL SON,Mirrored Aviator Sunglasses (Free Size),₹379,74% off
67,ROZZETTA CRAFT,"Mirrored, UV Protection Round Sunglasses (Free...",₹399,72% off
68,WROGN,Polarized Aviator Sunglasses (44),₹599,82% off
69,NuVew,UV Protection Sports Sunglasses (62),₹345,72% off
70,kingsunglasses,"UV Protection, Riding Glasses, Mirrored Wayfar...",₹213,82% off
71,ROZZETTA CRAFT,UV Protection Aviator Sunglasses (62),₹649,74% off
72,New Specs,UV Protection Round Sunglasses (Free Size),₹265,79% off
73,kingsunglasses,UV Protection Rectangular Sunglasses (55),₹189,85% off
74,ROZZETTA CRAFT,"UV Protection, Gradient Round Sunglasses (Free...",₹399,80% off
75,ROZZETTA CRAFT,"UV Protection, Riding Glasses Rectangular Sung...",₹449,79% off
76,kingsunglasses,"Mirrored, UV Protection Wayfarer Sunglasses (F...",₹269,82% off
77,PHENOMENAL,UV Protection Retro Square Sunglasses (Free Size),₹349,82% off
78,HRX by Hrithik Roshan,UV Protection Aviator Sunglasses (61),"₹2,309",30% off
79,VINCENT CHASE,by Lenskart UV Protection Rectangular Sunglass...,₹779,61% off
80,SUNBEE,"UV Protection, Polarized, Mirrored Wayfarer Su...",₹283,78% off
81,Lee Topper,UV Protection Rectangular Sunglasses (Free Size),₹219,78% off
82,ROZZETTA CRAFT,"UV Protection, Gradient Rectangular Sunglasses...",₹449,77% off
83,Flizz,UV Protection Retro Square Sunglasses (Free Size),₹389,82% off
84,GANSTA,UV Protection Aviator Sunglasses (57),₹314,84% off
85,ROYAL SON,Mirrored Aviator Sunglasses (55),₹379,74% off
86,VINCENT CHASE,"by Lenskart Polarized, UV Protection Aviator S...","₹1,179",41% off
87,AISLIN,"UV Protection, Gradient Butterfly, Retro Squar...",₹483,68% off
88,Fastrack,"Mirrored, UV Protection Wayfarer Sunglasses (F...",₹719,28% off
89,Fastrack,"Gradient, UV Protection Wayfarer Sunglasses (F...",₹719,20% off
90,CRYSTAL CART,"Polarized, UV Protection Retro Square Sunglass...",₹319,75% off
91,VINCENT CHASE,UV Protection Rectangular Sunglasses (52),₹699,65% off
92,PIRASO,UV Protection Over-sized Sunglasses (64),₹439,83% off
93,Fastrack,UV Protection Wayfarer Sunglasses (Free Size),₹639,20% off
94,Lee Topper,"Riding Glasses, Night Vision Wrap-around Sungl...",₹276,88% off
95,agera,UV Protection Aviator Sunglasses (55),₹242,78% off
96,Rich Club,Polarized Round Sunglasses (48),₹199,60% off
97,Fastrack,UV Protection Aviator Sunglasses (57),₹635,20% off
98,AISLIN,"UV Protection, Gradient Wayfarer, Retro Square...",₹498,70% off
99,ROZZETTA CRAFT,"Polarized, Riding Glasses Sports, Wrap-around ...",₹499,75% off

In [408]:
#Q5: Scrape 100 reviews data from flipkart.com for iphone11 phone.

#opening up flipkart.com website on automated chrome window
driver.get('https://www.flipkart.com/')

#finding element in search bar
search_field=driver.find_element_by_class_name("_3704LK") #search bar
search_field.send_keys("iphone 11")

#clicking on search icon
search_icon=driver.find_element_by_xpath("/html/body/div/div/div[1]/div[1]/div[2]/div[2]/form/div/button") #location search
search_icon.click()

#opening 1st iphone 11 black      
driver.get('https://www.flipkart.com/apple-iphone-11-black-128-gb/p/itm8244e8d955aba?pid=MOBFWQ6BKRYBP5X8&lid=LSTMOBFWQ6BKRYBP5X8X0KYUG&marketplace=FLIPKART&q=iphone+11&store=tyy%2F4io&srno=s_1_3&otracker=search&otracker1=search&fm=organic&iid=7c973bc3-05b6-4728-ab32-fde08e616cdb.MOBFWQ6BKRYBP5X8.SEARCH&ppt=hp&ppn=homepage&ssid=zlcvk3wocw0000001655572845466&qH=f6cdfdaa9f3c23f3')

#opening all review
driver.get('https://www.flipkart.com/apple-iphone-11-black-128-gb/product-reviews/itm8244e8d955aba?pid=MOBFWQ6BKRYBP5X8&lid=LSTMOBFWQ6BKRYBP5X8X0KYUG&marketplace=FLIPKART')

rating=[]                    #list to store rating
rev_sum=[]                  #list to store review summary
ful_rev=[]                    #list to store full review

for j in range (0,10):   
    time.sleep(5)
    #Lets extract all the tags having the rating
    rating_tags=driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq' or @class='_3LWZlK _1rdVr6 _1BLPMq' ]") #locating web element of rating
    
    #Now the rating is inside the tag extracted above
    for i in rating_tags:                 
        titles=i.text
        rating.append(titles)
       
    #Lets extract all the tags having the review summary
    revsum_tags=driver.find_elements_by_xpath("//p[@class='_2-N8zT']") #locating web element of review summary
    
    #Now the review summary is inside the tag extracted above
    for i in revsum_tags:
        products=i.text
        rev_sum.append(products) 
            
    #Lets extract all the tags having the full review
    fulrev_tags=driver.find_elements_by_xpath("//div[@class='t-ZTKy']") #locating web element of full review
    
    #Now the full review is inside the tag extracted above
    for i in fulrev_tags:
        r=i.text
        ful_rev.append(r)  
      
    #Now clicking on the next button
    if j==0:
        time.sleep(5)                             
        next_button=driver.find_element_by_xpath("/html/body/div[1]/div/div[3]/div/div/div[2]/div[13]/div/div/nav/a[11]/span")
        next_button.click()
        time.sleep(5)
    else:
        time.sleep(5)                            
        next_button=driver.find_element_by_xpath("/html/body/div[1]/div/div[3]/div/div/div[2]/div[13]/div/div/nav/a[12]/span")
        next_button.click()
        time.sleep(5)

pd.set_option("display.max_rows", None, "display.max_columns", None)                #To display the entire dataframe
df5=pd.DataFrame({'Rating':rating[0:100], 'Review Summary':rev_sum[0:100], 'Full Review': ful_rev[0:100]})
print("The first 100 ratings and reviews of iphone 11")
df5

The first 100 ratings and reviews of iphone 11

,Rating,Review Summary,Full Review
0,5,Simply awesome,Really satisfied with the Product I received.....
1,5,Best in the market!,Great iPhone very snappy experience as apple k...
2,5,Perfect product!,Amazing phone with great cameras and better ba...
3,5,Worth every penny,Previously I was using one plus 3t it was a gr...
4,5,Highly recommended,What a camera .....just awesome ..you can feel...
5,5,Fabulous!,This is my first iOS phone. I am very happy wi...
6,5,Great product,Amazing Powerful and Durable Gadget.\n\nI’m am...
7,5,Worth every penny,"i11 is worthy to buy, too much happy with the ..."
8,4,Good choice,So far it’s been an AMAZING experience coming ...
9,5,Highly recommended,iphone 11 is a very good phone to buy only if ...
10,5,Highly recommended,It's my first time to use iOS phone and I am l...
11,5,Perfect product!,It’s a must buy who is looking for an upgrade ...
12,5,Perfect product!,Value for money❤️❤️\nIts awesome mobile phone ...
13,5,Worth every penny,"Smooth like butter, camera like fantabulous, s..."
14,5,Perfect product!,It is just awesome mobile for this price from ...
15,5,Perfect product!,Iphone is just awesome.. battery backup is ver...
16,5,Worth every penny,Best budget Iphone till date ❤️ go for it guys...
17,5,Terrific,Really worth of money. i just love it. It is t...
18,5,Simply awesome,"Excellent camera, good performance, no lag. Th..."
19,5,Classy product,Totally in love with this ❤ the camera quality...
20,5,Highly recommended,It's my first time to use iOS phone and I am l...
21,5,Perfect product!,It’s a must buy who is looking for an upgrade ...
22,5,Perfect product!,Value for money❤️❤️\nIts awesome mobile phone ...
23,5,Worth every penny,"Smooth like butter, camera like fantabulous, s..."
24,5,Perfect product!,It is just awesome mobile for this price from ...
25,5,Perfect product!,Iphone is just awesome.. battery backup is ver...
26,5,Worth every penny,Best budget Iphone till date ❤️ go for it guys...
27,5,Terrific,Really worth of money. i just love it. It is t...
28,5,Simply awesome,"Excellent camera, good performance, no lag. Th..."
29,5,Classy product,Totally in love with this ❤ the camera quality...
30,5,Highly recommended,It's my first time to use iOS phone and I am l...
31,5,Perfect product!,It’s a must buy who is looking for an upgrade ...
32,5,Perfect product!,Value for money❤️❤️\nIts awesome mobile phone ...
33,5,Worth every penny,"Smooth like butter, camera like fantabulous, s..."
34,5,Perfect product!,It is just awesome mobile for this price from ...
35,5,Perfect product!,Iphone is just awesome.. battery backup is ver...
36,5,Worth every penny,Best budget Iphone till date ❤️ go for it guys...
37,5,Terrific,Really worth of money. i just love it. It is t...
38,5,Simply awesome,"Excellent camera, good performance, no lag. Th..."
39,5,Classy product,Totally in love with this ❤ the camera quality...
40,5,Highly recommended,It's my first time to use iOS phone and I am l...
41,5,Perfect product!,It’s a must buy who is looking for an upgrade ...
42,5,Perfect product!,Value for money❤️❤️\nIts awesome mobile phone ...
43,5,Worth every penny,"Smooth like butter, camera like fantabulous, s..."
44,5,Perfect product!,It is just awesome mobile for this price from ...
45,5,Perfect product!,Iphone is just awesome.. battery backup is ver...
46,5,Worth every penny,Best budget Iphone till date ❤️ go for it guys...
47,5,Terrific,Really worth of money. i just love it. It is t...
48,5,Simply awesome,"Excellent camera, good performance, no lag. Th..."
49,5,Classy product,Totally in love with this ❤ the camera quality...
50,5,Highly recommended,It's my first time to use iOS phone and I am l...
51,5,Perfect product!,It’s a must buy who is looking for an upgrade ...
52,5,Perfect product!,Value for money❤️❤️\nIts awesome mobile phone ...
53,5,Worth every penny,"Smooth like butter, camera like fantabulous, s..."
54,5,Perfect product!,It is just awesome mobile for this price from ...
55,5,Perfect product!,Iphone is just awesome.. battery backup is ver...
56,5,Worth every penny,Best budget Iphone till date ❤️ go for it guys...
57,5,Terrific,Really worth of money. i just love it. It is t...
58,5,Simply awesome,"Excellent camera, good performance, no lag. Th..."
59,5,Classy product,Totally in love with this ❤ the camera quality...
60,5,Highly recommended,It's my first time to use iOS phone and I am l...
61,5,Perfect product!,It’s a must buy who is looking for an upgrade ...
62,5,Perfect product!,Value for money❤️❤️\nIts awesome mobile phone ...
63,5,Worth every penny,"Smooth like butter, camera like fantabulous, s..."
64,5,Perfect product!,It is just awesome mobile for this price from ...
65,5,Perfect product!,Iphone is just awesome.. battery backup is ver...
66,5,Worth every penny,Best budget Iphone till date ❤️ go for it guys...
67,5,Terrific,Really worth of money. i just love it. It is t...
68,5,Simply awesome,"Excellent camera, good performance, no lag. Th..."
69,5,Classy product,Totally in love with this ❤ the camera quality...
70,5,Highly recommended,It's my first time to use iOS phone and I am l...
71,5,Perfect product!,It’s a must buy who is looking for an upgrade ...
72,5,Perfect product!,Value for money❤️❤️\nIts awesome mobile phone ...
73,5,Worth every penny,"Smooth like butter, camera like fantabulous, s..."
74,5,Perfect product!,It is just awesome mobile for this price from ...
75,5,Perfect product!,Iphone is just awesome.. battery backup is ver...
76,5,Worth every penny,Best budget Iphone till date ❤️ go for it guys...
77,5,Terrific,Really worth of money. i just love it. It is t...
78,5,Simply awesome,"Excellent camera, good performance, no lag. Th..."
79,5,Classy product,Totally in love with this ❤ the camera quality...
80,5,Highly recommended,It's my first time to use iOS phone and I am l...
81,5,Perfect product!,It’s a must buy who is looking for an upgrade ...
82,5,Perfect product!,Value for money❤️❤️\nIts awesome mobile phone ...
83,5,Worth every penny,"Smooth like butter, camera like fantabulous, s..."
84,5,Perfect product!,It is just awesome mobile for this price from ...
85,5,Perfect product!,Iphone is just awesome.. battery backup is ver...
86,5,Worth every penny,Best budget Iphone till date ❤️ go for it guys...
87,5,Terrific,Really worth of money. i just love it. It is t...
88,5,Simply awesome,"Excellent camera, good performance, no lag. Th..."
89,5,Classy product,Totally in love with this ❤ the camera quality...
90,5,Highly recommended,It's my first time to use iOS phone and I am l...
91,5,Perfect product!,It’s a must buy who is looking for an upgrade ...
92,5,Perfect product!,Value for money❤️❤️\nIts awesome mobile phone ...
93,5,Worth every penny,"Smooth like butter, camera like fantabulous, s..."
94,5,Perfect product!,It is just awesome mobile for this price from ...
95,5,Perfect product!,Iphone is just awesome.. battery backup is ver...
96,5,Worth every penny,Best budget Iphone till date ❤️ go for it guys...
97,5,Terrific,Really worth of money. i just love it. It is t...
98,5,Simply awesome,"Excellent camera, good performance, no lag. Th..."
99,5,Classy product,Totally in love with this ❤ the camera quality...

In [409]:
#Q6. Scrape data for first 100 sneakers you find when you visit flipkart.com and search for “sneakers” in the search field.

#opening up flipkart.com website on automated chrome window
driver.get('https://www.flipkart.com/')

#finding element in search bar
search_field=driver.find_element_by_class_name("_3704LK") #search bar
search_field.send_keys("sneakers")

#clicking on search icon
search_icon=driver.find_element_by_xpath("/html/body/div/div/div[1]/div[1]/div[2]/div[2]/form/div/button") #location search
search_icon.click()

brand=[]                    #list to store brand
product=[]                  #list to store product description
price=[]                    #list to store price
discount=[]                 #list to store discount

for j in range (0,3):
    time.sleep(5)
    #Lets extract all the tags having the brand
    brand_tags=driver.find_elements_by_xpath("//div[@class='_2WkVRV']") #locating web element of brand
    
    #Now the text of the brand is inside the tag extracted above
    for i in brand_tags:                
        titles=i.text
        brand.append(titles)
    
    #Lets extract all the tags having the product description
    product_tags=driver.find_elements_by_xpath("//div[@class='_2B099V']/a[1]") #locating web element of product description
    
    #Now the text of the product description is inside the tag extracted above
    for i in product_tags:
        products=i.text
        product.append(products)
            
    #Lets extract all the tags having the price
    price_tags=driver.find_elements_by_xpath("//div[@class='_30jeq3']") #locating web element of price
    
    #Now the text of the price is inside the tag extracted above
    for i in price_tags:
        prices=i.text
        price.append(prices)
    
    #Lets extract all the tags having the discount
    discount_tags=driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']/span") #locating web element of discount
    
    #Now the text of the discount is inside the tag extracted above
    for i in discount_tags:
        discounts=i.text
        discount.append(discounts)
    
    #Now clicking on the next button
    if j==0:
        time.sleep(5)
        next_button=driver.find_element_by_xpath("/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[11]/span")
        next_button.click()
        time.sleep(5)
    else:
        time.sleep(5)
        next_button=driver.find_element_by_xpath("/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[12]/span")
        next_button.click()
        time.sleep(5)

pd.set_option("display.max_rows", None, "display.max_columns", None)                #To display the entire dataframe
df6=pd.DataFrame({'Brand':brand[0:100], 'Product description':product[0:100], 'Price': price[0:100], 'Discount Provided': discount[0:100]})
print("The data for sneakers-")
df6

The data for sneakers-

,Brand,Product description,Price,Discount Provided
0,Chevit,494 Perfect Sports Shoes for Running Training ...,₹299,70% off
1,Scull Wings,Sneakers For Men,₹439,70% off
2,BRUTON,Lightweight Pack Of 1 Trendy Sneakers Sneakers...,₹188,68% off
3,Magnolia,Sneakers For Men,₹374,62% off
4,BIRDE,"Stylish Comfortable Lightweight, Breathable Wa...",₹314,68% off
5,BRUTON,Modern Trendy Sneakers Shoes Sneakers For Men,₹299,76% off
6,Layasa,Sneakers For Men,₹399,60% off
7,Roadster,Men Blue Solid Sneakers Sneakers For Men,"₹1,299",53% off
8,URBANBOX,Sneakers Sneakers For Men,₹198,80% off
9,BRUTON,Modern Trendy Sneakers Shoes Sneakers For Men,₹269,79% off
10,Labbin,Sneakers For Men,₹499,50% off
11,EZDEZARIO,Fashion Outdoor Canvas Casual Light Weight Lac...,₹449,55% off
12,Robbie jones,Casual Sneakers Green Shoes For Men And Boys S...,₹499,50% off
13,Robbie jones,Casual Sneakers Canvas Shoes For Men Sneakers ...,₹499,50% off
14,Kraasa,Shark-41 Sneakers For Men,₹479,52% off
15,luxury fashion,Luxuryfashion casual sneaker shoes Sneakers Fo...,₹474,63% off
16,aadi,Sneakers For Men,₹319,68% off
17,Robbie jones,Sneakers For Men,₹499,50% off
18,D-SNEAKERZ,"Casual , Partywear Sneakers Shoes For Men's An...",₹299,54% off
19,RapidBox,Sneakers For Men,₹680,31% off
20,Robbie jones,Casual Sneakers White Shoes For Men Sneakers F...,₹499,50% off
21,Kraasa,Series 7 Sneakers For Men,₹479,52% off
22,ASTEROID,Original Luxury Branded Fashionable Men's Casu...,₹499,75% off
23,coma,Sneakers For Men,₹599,60% off
24,Robbie jones,Sneakers For Men,₹499,50% off
25,KWIK FIT,Kwik FIT casual sneaker shoes and partywear sh...,₹397,80% off
26,Robbie jones,Sneakers For Men,₹499,50% off
27,Kirjak,1602 stylish black men Sneakers For Men,₹569,71% off
28,BIRDE,"Stylish Comfortable Lightweight, Breathable Ca...",₹299,70% off
29,Kzaara,Sneakers For Men,₹254,74% off
30,U.S. POLO ASSN.,PANAL Sneakers For Men,"₹1,745",41% off
31,TrendWalk,Original Luxury Branded Fashionable Men's Casu...,₹540,72% off
32,SCATCHITE,Sneakers Sneakers For Men,₹419,58% off
33,bluemaker,casual for men Sneakers For Men,₹599,40% off
34,aadi,Sneakers For Men,₹299,70% off
35,EZDEZARIO,Casual Shoes for Men Sneakers For Men,₹399,60% off
36,Numenzo,411 Casual Sneakers For Men,₹402,79% off
37,BRUTON,Lattest Sneakers Shoe Sneakers For Men,₹269,79% off
38,CLYMB,Sneakers For Men,₹519,65% off
39,Chevit,Unique & Perfect Collection Combo Pack of 02 S...,₹474,68% off
40,corsac,STYLISH MENS BLACK SNEAKER Sneakers For Men,₹499,66% off
41,HOTSTYLE,Sneakers For Men,₹245,75% off
42,Dicy,Sneakers For Men,₹299,50% off
43,BRUTON,Combo Pack of 2 Casual Sneakers For Men,₹499,80% off
44,Roadster,Sneakers For Men,"₹1,119",65% off
45,Kraasa,"Casuals, Canvas, Partywear Sneakers For Men",₹479,52% off
46,U.S. POLO ASSN.,Sneakers For Men,"₹1,952",34% off
47,Zixer,Exclusive dancing sneaker For Boys||Funky danc...,₹666,33% off
48,PUMA,Puma Rebound LayUp SL Sneakers For Men,"₹2,667",46% off
49,AKIMBO,A-SHOES-205 Sneakers For Men,₹549,45% off
50,BRUTON,Sneaker Sneakers For Men,₹281,78% off
51,Absolutee shoes,Sneakers For Men,₹699,53% off
52,Airland,1259 smart black lace-ups sneakers for men Sne...,₹210,57% off
53,Layasa,Sneakers For Men,₹399,60% off
54,BIRDE,"Stylish Comfortable Lightweight, Breathable Wa...",₹356,64% off
55,LuvShus,Sneakers For Men,₹599,40% off
56,Echor,Men's Sneakers Fashion Lightweight Running Sho...,₹485,51% off
57,Dizzler,Sneakers For Men,₹495,31% off
58,KNIGHTWING,Stylish Comfortable Sneakers For Men Sneakers ...,₹699,61% off
59,BRUTON,Perfect & Affordable Combo Pack of 02 Pairs Sn...,₹416,82% off
60,ASTEROID,Original Luxury Branded Fashionable Men's Casu...,₹499,50% off
61,BRUTON,Combo Pack Of 2 Latest Stylish Casual Shoes fo...,₹499,80% off
62,Robbie jones,Casual Sneakers Shoes For Men And Boys Sneaker...,₹499,50% off
63,EZDEZARIO,Casual Sneakers Shoes For Men Sneakers For Men...,₹399,60% off
64,RapidBox,Sneakers For Men,₹665,33% off
65,Echor,Men's Sneakers Fashion Lightweight Running Sho...,₹539,46% off
66,CAMPUS,KING PRO Sneakers For Men,₹839,23% off
67,BRUTON,Modern Trendy Sneakers Shoes Sneakers For Men,₹299,76% off
68,PUMA,x KL Seattle Sneakers For Men,"₹2,981",33% off
69,WOODLAND,Sneakers For Men,"₹1,754",29% off
70,DUNKASTON,Sneakers For Men,₹389,74% off
71,Chevit,Men's Combo Pack of 02 Shoes for Men Casual Sn...,₹470,57% off
72,ADIDAS,STREET ICON M Sneakers For Men,"₹2,350",34% off
73,LE GREEM,Comfortable & Ultra Light Weight Sneaker Sneak...,₹499,50% off
74,LEVI'S,Men's Lancer Sneakers Sneakers For Men,"₹1,439",55% off
75,BRUTON,Combo Pack Of 3 Latest Casual Shoes Sneakers F...,₹499,83% off
76,U.S. POLO ASSN.,CLARKIN Sneakers For Men,"₹1,745",41% off
77,Chevit,516 Trendy Star Perfect Sneakers For Men,₹279,65% off
78,WHITE WALKERS,Stylish & Trending Outdoor Walking Comfortable...,₹599,50% off
79,ASTEROID,Wings Print Premium Fancy Stylish Fashion Snea...,₹549,72% off
80,U.S. POLO ASSN.,CLARKIN 2.0 Sneakers For Men,"₹1,958",34% off
81,AMICO,Sneakers For Men,₹466,53% off
82,asics,LYTECOURT Sneakers For Men,"₹2,630",41% off
83,HOC,Luxury Fashionable Breathable Casual Sneakers ...,₹479,76% off
84,ZF Klub,Sneakers For Men,₹379,62% off
85,PUMA,Puma Smash Vulc Sneakers For Men,"₹2,089",45% off
86,Shoes Bank,White Sneaker For Men's/Boy's Sneakers For Men,₹298,70% off
87,Roadster,Men Blue Solid Sneakers Sneakers For Men,"₹1,299",53% off
88,Numenzo,Sneakers For Men,₹509,83% off
89,SPARX,Sneakers For Men,₹658,15% off
90,KNIGHT WALKERS,SS1100 Sneakers For Men,₹699,65% off
91,EZDEZARIO,Fashion Outdoor Canvas Casual Light Weight Lac...,₹449,55% off
92,Creer,Casual White Shoes Sneakers For Men,₹348,76% off
93,PROVOGUE,Sneakers For Men,₹579,55% off
94,LE GREEM,Comfortable & Ultra Light Weight Sneaker Sneak...,₹499,50% off
95,Chevit,Unique & Perfect Collection Combo Pack of 02 S...,₹474,68% off
96,corsac,STYLISH MENS BLACK TRENDY SNEAKER FOR MENS Sne...,₹499,66% off
97,AMICO,Sneakers For Men,₹466,53% off
98,Bretton,Sneakers For Men,₹251,74% off
99,BRUTON,Perfect & Affordable Combo Pack of 02 Pairs Sn...,₹416,82% off

In [418]:
#Q7. Go to the link - https://www.myntra.com/shoes.Set second Price filter and Color filter to “Black”

#opening up myntra.com website on automated chrome window
driver.get('https://www.myntra.com/shoes')

#applying price filter
driver.get('https://www.myntra.com/shoes?rf=Price%3A6637.0_13125.0_6637.0%20TO%2013125.0')

#applying color filter
driver.get('https://www.myntra.com/shoes?f=Color%3ABlack_36454f&rf=Price%3A6637.0_13125.0_6637.0%20TO%2013125.0')

brand=[]                    #list to store brand
product=[]                  #list to store product description
price=[]                    #list to store price

for j in range (0,2):          
    time.sleep(5)
    #Lets extract all the tags having the brand
    brand_tags=driver.find_elements_by_xpath("//h3[@class='product-brand']") #locating web element of brand
    
    #Now the text of the brand is inside the tag extracted above
    for i in brand_tags:                 
        titles=i.text
        brand.append(titles)
    
    #Lets extract all the tags having the product description
    product_tags=driver.find_elements_by_xpath("//h4[@class='product-product']") #locating web element of product description
    
    #Now the text of the product description is inside the tag extracted above
    for i in product_tags:
        products=i.text
        product.append(products)
            
    #Lets extract all the tags having the price
    price_tags=driver.find_elements_by_xpath("//div[@class='product-price']/span[1]") #locating web element of price
    
    #Now the text of the price is inside the tag extracted above
    for i in price_tags:
        prices=i.text.split()[1]
        pr=prices.replace('Rs.','')
        price.append(''.join(pr))
    
    #Now clicking on the next button
    time.sleep(5)
    next_button=driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/main/div[3]/div[2]/div/div[2]/section/div[2]/ul/li[12]/a")
    next_button.click()
    time.sleep(5)
        
s_no=[]
for k in range(1,101):
    s_no.append(k)

pd.set_option("display.max_rows", None, "display.max_columns", None)                #To display the entire dataframe
df7=pd.DataFrame({'Brand':brand[0:100], 'Product description':product[0:100], 'Price': price[0:100]}, index=s_no)
print("The data for shoes-")
df7

The data for shoes-

                    Brand                       Product description  Price
1                Skechers                Men Max Cushioning Running   8999
2                    Nike            Men Zoom C Pro HC Tennis Shoes   7116
3                Skechers                  Men ENIGMA Running Shoes   7124
4                    Nike            Women Pegasus 39 Running Shoes   8920
5                    Puma                         Men Running Shoes   9999
6                    Nike                Women React Escape Running   9196
7                    Nike            Women React MR 3 Running Shoes   8396
8                    Puma              Eternity Nitro Running Shoes  12999
9                    Puma                Men M Nitro Running Shoess  12999
10               Skechers                Men PREMIER-VANTAG Running   6999
11           UNDER ARMOUR              Men UA Charged Vantage 2 Run   7999
12                   Puma              Men Velocity Nitro 2 Running  10999
13                 ADIDAS              Men Solar Glide 4 ST Running  11249
14                   Puma             Electrify Nitro Running Shoes   9999
15           UNDER ARMOUR             Men Charged Rouge 3 Run Shoes   6999
16           UNDER ARMOUR                Men Charged Breeze Running   8999
17               Skechers             BIONICTRAILROAD TrekkingShoes   6799
18                  ASICS               Unisex Rote Japan Lyte FF 2   7199
19                   Puma                Men Velocity Nitro Running   7199
20                   Puma                Women Running Sports Shoes   7499
21                   Vans                Men Colourblocked Sneakers   8249
22           UNDER ARMOUR             Women Aurora 2 Training Shoes   6999
23           UNDER ARMOUR            Men HOVR Sonic SE Running Shoe   9999
24         Tommy Hilfiger                     Women Leather Loafers   6839
25           UNDER ARMOUR               Women Charged Pursuit 3 Run   6999
26         Tommy Hilfiger                      Men Leather Sneakers   6799
27                 ADIDAS                        Women Sports Shoes   9899
28           UNDER ARMOUR              Women Charged Breeze Running   8999
29         Tommy Hilfiger            Men JEANS RETRO BASKET Sneaker   7309
30         Tommy Hilfiger                              Men Sneakers   6799
31               Columbia            Men FACET OUTDRY Trekking Shoe  12999
32           UNDER ARMOUR             Women Hovr Sonic SE Run Shoes   9999
33           Hush Puppies         Men Solid Leather Formal Slip-Ons   7999
34            New Balance                 Women Flash Running Shoes   7999
35                 ADIDAS             Women Supernova Running Shoes   9999
36           Hush Puppies                 Men Solid Formal Slip-Ons   7999
37                 ADIDAS               Women Solar Glide 5 Running   8399
38                   Puma              Women Liberate NITRO Running   9999
39                   Geox        Men Textured Leather Driving Shoes   9891
40                   Geox                      Men Leather Sneakers   9891
41              J.FONTINI                       Men Leather Fashion   8490
42                   Geox        Men Textured Leather Driving Shoes   7343
43           UNDER ARMOUR            W omen TriBase Reign 4 Running  11999
44            New Balance                   Women 680 Running Shoes   7999
45   FORCLAZ By Decathlon                        TREKKING 100 Boots   6999
46                   Geox        Men Textured Leather Driving Shoes   7693
47                   Geox        Men Textured Leather Driving Shoes   6993
48                   Geox     Men Textured Leather Slip-On Sneakers   8991
49                   Geox        Men Textured Leather Driving Shoes   7693
50   EVADICT By Decathlon                         Men Running Shoes  10289
51   EVADICT By Decathlon                         Men Running Shoes  10289
52               Columbia             Women REDMOND V2 TrekkingShoe   7999
53                 Clarks                                             7499
54                   Geox            Women Textured Leather Loafers   7492
55                Saint G                       Stiletto Heel Mules   8075
56                   Xtep                         Men Running Shoes   7699
57                   Geox                 Men Perforations Sneakers  12591
58                   Geox                 Men Leather Driving Shoes   8393
59    KIPRUN By Decathlon                         Men Running Shoes   8685
60                Saint G                     Leather Block Sandals   9810
61                   Geox                     Leather Block Sandals   7117
62                Bugatti                         Men Walking Shoes   6999
63                 Clarks                      Men Leather Slip-Ons   9999
64                   Geox                      Men Leather Sneakers  11691
65                   Geox                      Men Leather Sneakers  12591
66              J.FONTINI              Men Textured Leather Loafers   8490
67                   Geox                      Men Leather Sneakers  11691
68                  ASICS                       Women Running Shoes   7599
69                  ASICS                       Women Running Shoes   7999
70                 Clarks          Men Solid Leather Formal Loafers   7999
71                  MANGO            Embellish Mid-Top Heeled Boots   7990
72                Bugatti           Men Solid Leather Formal Derbys   9999
73                   Geox                              Men Sneakers   6999
74               DAVINCHI  Men Textured Leather Formal Loafer Shoes   6990
75            New Balance               Women Training or Gym Shoes   7999
76                  Metro                  Women Block Heeled Boots   6990
77                   Geox                 Women Solid Leather Heels   6742
78                 Clarks              Men Leather Slip-On Sneakers   8999
79                   Geox                    Women Ballerinas Flats   8055
80                   Geox            Women Textured Leather Loafers   7117
81         Louis Philippe               Men Leather Formal Slip-Ons   6799
82                Saint G            Suede Leather Block Heel Boots  10355
83                 Kenkoh                  Leather Flatform Sandals  10400
84   Quechua By Decathlon                        Men Trekking Shoes   9999
85                fitflop      Embellished Leather Flatform Sandals   8299
86               Columbia            PEAKFREAK OUTDRY Trekking Shoe   9999
87               DAVINCHI               Men Formal Leather Slip-Ons   8990
88                   Geox                       Leather Block Pumps   8992
89                   Geox              Textured Leather Block Pumps   8992
90               DAVINCHI       Men Textured Formal Leather Loafers   8990
91                   Geox                     Leather Block Sandals   8242
92                   Geox                            Flatform Heels  10791
93                   Geox            Women Leather Slip-On Sneakers   8242
94                   ECCO                       Leather Block Pumps   7499
95                   Geox                    Women Ballerinas Flats   9891
96                   Geox                      Women Open Toe Flats   6742
97                   Geox              Men Slip-On Formal Moccasins   6993
98              J.FONTINI                Men Leather Formal Loafers   7490
99               DAVINCHI                  Men Formal Slip-On Shoes   6990
100              DAVINCHI                Solid Leather Formal Boots   6990

In [426]:
#Q8. Go to webpage https://www.amazon.in/. Enter “Laptop” in the search field and then click the search icon..Then set CPU Type filter to “Intel Core i7”

#opening up amazon.com website on automated chrome window
driver.get('https://www.amazon.in/')

#finding element in search bar
search_field=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[2]/div[1]/input") #search bar
search_field.send_keys("Laptop")

#clicking on search icon
search_icon=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input") #location search
search_icon.click()

#applying CPU type filter
driver.get('https://www.amazon.in/s?k=Laptop&rh=n%3A1375424031%2Cp_n_feature_thirteen_browse-bin%3A12598163031&dc&ds=v1%3AxTt2m2mUIWd5kdMJ9QpZHMJidMbNo38L1XV8BEQuuQs&crid=3FVR38U3X6BI7&qid=1655579220&rnid=12598141031&sprefix=laptop%2Caps%2C809&ref=sr_nr_p_n_feature_thirteen_browse-bin_13')

titles=[]                  #list to store titles
rating=[]                  #list to store rating
price=[]                   #list to store price

time.sleep(5)
#Lets extract all the tags having the titles
title_tags=driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']") #locating web element of title

#Now the text title is inside the tag extracted above
for i in title_tags[0:10]:
    title=i.text
    titles.append(title)

time.sleep(5)
#Lets extract all the tags having the ratings
rating_tags=driver.find_elements_by_xpath("//span[@class='a-icon-alt']") #locating web element of rating

#Now the rating is inside the tag extracted above
for i in rating_tags[0:10]:
    rate=i.text                                   #rating was not being extracted
    rating.append("Not Available")

#Lets extract all the tags having the price
price_tags=driver.find_elements_by_xpath("//span[@class='a-price-whole']") #locating web element of price

#Now the price is inside the tag extracted above
for i in price_tags[0:10]:
    pr=i.text
    price.append(pr)

pd.set_option("display.max_rows", None, "display.max_columns", None)  #To display the entire dataframe
df8=pd.DataFrame({'Title':titles, 'Rating':rating, 'Price':price})
print("The data for laptop with Intel Core i7")
df8

The data for laptop with Intel Core i7

                                               Title         Rating   Price
0  ASUS TUF Gaming F15 (2021), 15.6" (39.62 cms) ...  Not Available  83,990
1  ASUS VivoBook 14 (2021), 14-inch (35.56 cms) F...  Not Available  57,490
2  Lenovo IdeaPad 5 Pro 11th Gen Intel Core i7 14...  Not Available  74,512
3  Samsung Galaxy Book2 Intel 12th Gen core i7 39...  Not Available  79,990
4  LG Gram 17 Intel Evo 11th Gen i7 Thin & Light ...  Not Available  88,490
5  HP Pavilion x360 11th Gen Intel Core i7 14 inc...  Not Available  84,490
6  LG Gram 16 Intel Evo 11th Gen i7 Thin & Light ...  Not Available  86,490
7  ASUS Vivobook X515JA-EJ701WS Intel Core I7-106...  Not Available  57,290
8  HP Pavilion 15 12th Gen Intel Core i7 16GB SDR...  Not Available  89,009
9  Lenovo IdeaPad Flex 5 11th Gen Intel Core i7 1...  Not Available  81,490

In [427]:
#Q9: Write a python program to scrape data for first 10 job results for Data Scientist Designation in Noida location. You have to scrape company name, No. of days ago when job was posted, Rating of the company.
    
#opening up ambitionbox.com website on automated chrome window
driver.get('https://www.ambitionbox.com/')
 
#clicking on job option                 
job_option=driver.find_element_by_xpath("/html/body/div[1]/nav/nav/a[6]") #location search
job_option.click()

time.sleep(5)
#finding element in search bar
search_field=driver.find_element_by_xpath("/html/body/div/div/div/div[2]/div[1]/div[1]/div/div/div/div/span/input") #search bar
search_field.send_keys("Data Scientist")

#clicking on search icon                  
search_icon=driver.find_element_by_xpath("/html/body/div/div/div/div[2]/div[1]/div[1]/div/div/div/button/span") #location search
search_icon.click()

time.sleep(5)
#clicking on location icon 
loc_icon=driver.find_element_by_xpath("/html/body/div/div/div/div[2]/div[1]/div[2]/div[1]/div/div/div/div[2]/div[1]/p") #location search
loc_icon.click()

time.sleep(5)
#finding location in search bar
search_fields=driver.find_element_by_xpath("/html/body/div/div/div/div[2]/div[1]/div[2]/div[1]/div/div/div/div[2]/div[2]/div/div[2]/input") #search bar
search_fields.send_keys("Noida")

time.sleep(5)
#clicking on Noida
search=driver.find_element_by_xpath("/html/body/div/div/div/div[2]/div[1]/div[2]/div[1]/div/div/div/div[2]/div[2]/div/div[3]/div[1]/div[1]/div") #location search
search.click()

company=[]                  #list to store company name
time_period=[]             #list to store when it was posted
rating=[]                  #list to store rating

time.sleep(5)
#Lets extract all the tags having the company names
company_tags=driver.find_elements_by_xpath("//p[@class='company body-medium']") #locating web element of company name

#Now the text of the comapny name is inside the tag extracted above
for i in company_tags[0:10]:
    title=i.text
    company.append(title)

#Lets extract all the tags having the time period
time=driver.find_elements_by_xpath("//div[@class='other-info']/span[1]") #locating web element of time period

#Now the tim period is inside the tag extracted above
for i in time[0:10]:
    t=i.text
    time_period.append(t)

#Lets extract all the tags having the rating
rate_tags=driver.find_elements_by_xpath("//span[@class='body-small']") #locating web element of rating

#Now the text of the rating is inside the tag extracted above
for i in rate_tags[0:10]:
    r=i.text
    rating.append(r)

s_no=[]
for k in range(1,11):
    s_no.append(k)
    
pd.set_option("display.max_rows", None, "display.max_columns", None)                #To display the entire dataframe
df9=pd.DataFrame({'Company':company, 'No. of days ago when job was posted':time_period, 'Rating':rating}, index=s_no)
print("The data for Data Scientist Job at Noida”)
df9

The data for Data Scientist Job at Noida”

,Company,No. of days ago when job was posted,Rating
1,Intel Technology India Pvt Ltd,1d ago,4.4
2,Schneider Electric India Pvt. Ltd.,1d ago,4.2
3,IBM India Pvt. Limited,1d ago,4.2
4,SAP India Pvt.Ltd,10d ago,4.4
5,Concentrix Daksh Services India Private Limited.,2d ago,4.1
6,Sanofi India Ltd,11d ago,4.5
7,Walmart Labs,4d ago,4.2
8,Walmart Labs,4d ago,4.2
9,Tesco Bengaluru,3d ago,4.2
10,Tesco Bengaluru,3d ago,4.2

In [435]:
#Q10. Write a python program to scrape the salary data for Data Scientist designation. You have to scrape Company name, Number of salaries, Average salary, Minsalary, Max Salary.

#opening up ambitionbox.com website on automated chrome window
driver.get('https://www.ambitionbox.com/')

#clicking on salary option                  
salary_option=driver.find_element_by_xpath("/html/body/div[1]/nav/nav/a[4]") #location search
salary_option.click()

time.sleep(5)
#finding element in search bar
search_field=driver.find_element_by_xpath("//div[@class='searchbox-wrapper']/span/input") #search bar
search_field.send_keys("Data Scientist")

time.sleep(5)
#clicking on Data Scientist option 
ds=driver.find_element_by_xpath("/html/body/div/div/div/main/section[1]/div[2]/div[1]/span/div/div/div[1]/div/div/p") #location search
ds.click()

company=[]             #list to store company name
tot_sal=[]             #list to store total number ofsalary
avg_sal=[]             #list to store average salary
min_sal=[]             #list to store minimum salary
max_sal=[]             #list to store maximum salary
exp=[]                 #list to store experience required

time.sleep(5)
#Lets extract all the tags having the company names
company_tags=driver.find_elements_by_xpath("//div[@class='name']/a") #locating web element of company name

#Now the text of the company name is inside the tag extracted above
for i in company_tags[0:10]:
    title=i.text
    company.append(title)

#Lets extract all the tags having the total number of salary
tot=driver.find_elements_by_xpath("//div[@class='name']/span") #locating web element of total number of salary

#Now the total no of salary  is inside the tag extracted above
for i in tot[0:10]:
    t=i.text.split()[2]
    tot_sal.append(''.join(t))

#Lets extract all the tags having the average salary
avg=driver.find_elements_by_xpath("//p[@class='averageCtc']") #locating web element of average salary

#Now the average salary is inside the tag extracted above
for i in avg[0:10]:
    r=i.text
    avg_sal.append(r)
    
#Lets extract all the tags having the minimum salary
min=driver.find_elements_by_xpath("//div[@class='salary-values']/div[1]") #locating web element of minimum salary

#Now the minimum salary is inside the tag extracted above
for i in min[0:10]:
    m=i.text
    min_sal.append(m)

#Lets extract all the tags having the maximum salary
max=driver.find_elements_by_xpath("//div[@class='salary-values']/div[2]") #locating web element of maximum salary

#Now the maximum salary is inside the tag extracted above
for i in max[0:10]:
    mx=i.text
    max_sal.append(mx)

#Lets extract all the tags having the experience
exp_tags=driver.find_elements_by_xpath("//div[@class='salaries sbold-list-header']") #locating web element of experience

#Now the experience is inside the tag extracted above
for i in exp_tags[0:10]:
    l=len(i.text.split())
    ex=i.text.split()[3:l-1]
    exp.append(' '.join(ex))

s_no=[]
for k in range(1,11):
    s_no.append(k)
    
pd.set_option("display.max_rows", None, "display.max_columns", None)                #To display the entire dataframe
df10=pd.DataFrame({'Company':company, 'Total Salary Record':tot_sal, 'Average Salary':avg_sal, 'Minimum Salary':min_sal, 'Maximum Salary':min_sal, 'Experience':exp}, index=s_no)
print("The salary for Data Scientist Job”)
df10

The salary for Data Scientist Job”

,Company,Total Salary Record,Average Salary,Minimum Salary,Maximum Salary,Experience
1,Walmart,12,₹ 30.2L,₹ 25.0L,₹ 25.0L,3 yrs
2,Ab Inbev,33,₹ 20.6L,₹ 15.0L,₹ 15.0L,3-4 yrs
3,American Express,10,₹ 19.9L,₹ 14.1L,₹ 14.1L,4 yrs
4,ZS,15,₹ 16.7L,₹ 11.0L,₹ 11.0L,2 yrs
5,Optum,33,₹ 16.1L,₹ 11.0L,₹ 11.0L,3-4 yrs
6,Reliance Jio,21,₹ 15.7L,₹ 5.6L,₹ 5.6L,3-4 yrs
7,Fractal Analytics,83,₹ 15.4L,₹ 10.0L,₹ 10.0L,2-4 yrs
8,Tiger Analytics,50,₹ 14.8L,₹ 9.0L,₹ 9.0L,2-4 yrs
9,UnitedHealth,57,₹ 14.0L,₹ 8.3L,₹ 8.3L,2-4 yrs
10,EXL Service,10,₹ 13.3L,₹ 8.9L,₹ 8.9L,4 yrs